export const PROCEDURE_LABELS: Record<string, string> = {
  'extremstellen-nachweis': 'Bestimme die Extremstellen und weise deren Art nach.',
  'extremstellen-eigenstaendig': 'Bestimme die Extremstellen und weise deren Art nach.',
  'extremstellen-vzw': 'Bestimme die Extremstellen mithilfe des Vorzeichenwechselkriteriums.',
  'extremstellen-kandidaten': 'Bestimme die Kandidaten für Extremstellen.',
  'wendestellen-nachweis': 'Bestimme die Wendestellen der Funktion.',
  'wendetangente': 'Bestimme die Wendetangente der Funktion.',
  'wendestelle-vzw': 'Bestimme die Wendestellen mithilfe des Vorzeichenwechselkriteriums.',
  'monotonie': 'Bestimme die Intervalle, in denen f streng monoton steigend bzw. fallend ist.',
  'monotonie-intervall': 'Zeige, dass f auf dem angegebenen Intervall streng monoton steigend bzw. fallend ist.',
  'kurvendiskussion': 'Führe eine vollständige Kurvendiskussion durch.',
  'kruemmung': 'Untersuche das Krümmungsverhalten der Funktion.',
  'keine-extremstelle': 'Untersuche, ob die Funktion Extremstellen besitzt.',
  'optimierung-intervall': 'Bestimme das Optimum im gegebenen Intervall.',
  'waagerechte-tangente': 'Bestimme die Stellen mit waagerechter Tangente.',
  'kombination-kriterien': 'Wende die Kriterien kombiniert an.',
  'parameterfunktion': 'Untersuche die Parameterfunktion.',
  'wendepunkt-dreiecksflaeche': 'Bestimme den Wendepunkt und berechne die Dreiecksfläche.',
};
