import type { ModuleConfig } from './types/progress.js';

export const MODULE_CONFIGS: ModuleConfig[] = [
  {
    id: 'monotonie',
    title: 'Monotonie',
    description: 'Zusammenhang zwischen f\' und dem Steigungsverhalten von f',
    order: 1,
    exerciseTypes: ['identify-points', 'true-false', 'reverse-inference', 'criteria-quiz', 'step-by-step', 'context-interpretation', 'graph-sketch'],
    competencyLevels: ['K1', 'K2', 'K3', 'K4', 'K5'],
  },
  {
    id: 'extremstellen',
    title: 'Lokale Extremstellen',
    description: 'Hoch- und Tiefpunkte bestimmen: f\' = 0 und hinreichende Bedingungen',
    order: 2,
    exerciseTypes: ['graph-assignment', 'identify-points', 'true-false', 'reverse-inference', 'criteria-quiz', 'step-by-step', 'transformation-reasoning'],
    competencyLevels: ['K1', 'K2', 'K3', 'K4', 'K5'],
  },
  {
    id: 'wendestellen',
    title: 'Wendestellen & Krümmung',
    description: 'Wendepunkte bestimmen: f\'\' = 0, Links-/Rechtskurve, Wendetangente',
    order: 3,
    exerciseTypes: ['graph-assignment', 'identify-points', 'true-false', 'reverse-inference', 'criteria-quiz', 'step-by-step'],
    competencyLevels: ['K1', 'K2', 'K3', 'K4', 'K5'],
  },
  {
    id: 'zusammenhang',
    title: 'Zusammenhang f ↔ f\' ↔ f\'\'',
    description: 'Graphen zuordnen und Rückschlüsse ziehen',
    order: 4,
    exerciseTypes: ['graph-assignment', 'true-false', 'reverse-inference'],
    competencyLevels: ['K1', 'K3'],
  },
  {
    id: 'kurvendiskussion',
    title: 'Kurvendiskussion',
    description: 'Vollständige Untersuchung: Nullstellen, Extrema, Wendepunkte, Skizze',
    order: 5,
    exerciseTypes: ['step-by-step', 'graph-sketch', 'contradiction-argument'],
    competencyLevels: ['K3', 'K4', 'K5'],
  },
  {
    id: 'sachkontext',
    title: 'Sachzusammenhänge',
    description: 'Mathematische Begriffe im Alltag: interpretieren, formalisieren, optimieren',
    order: 6,
    exerciseTypes: ['context-interpretation', 'step-by-step'],
    competencyLevels: ['K3', 'K4'],
  },
  {
    id: 'quiz',
    title: 'Kriterien-Quiz',
    description: 'Alle Bedingungen und Definitionen sicher abrufen',
    order: 7,
    exerciseTypes: ['criteria-quiz'],
    competencyLevels: ['K1', 'K3', 'K5'],
  },
];
